### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by LZQ1204** [fdshan/cv_project#1]
请问您，dgcnn的可视化是怎么实现的

**Comment by fdshan** [comment]
不好意思，回答的有些晚，希望没有耽误您的时间。

把点的信息输出到txt里，然后用meshlab实现的可视化。

dgcnn_pytorch的原作者昨天在代码里加上了可视化的部分，您可以去看看。链接：https://github.com/AnTao97/dgcnn.pytorch
我也提问过相关可视化的问题在issue里，链接：https://github.com/AnTao97/dgcnn.pytorch/issues/26

**Comment by LZQ1204** [comment]
非常感谢！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fdshan/cv_project"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 上午9:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fdshan/cv_project] 可视化 (#1)





 
不好意思，回答的有些晚，希望没有耽误您的时间。
 
把点的信息输出到txt里，然后用meshlab实现的可视化。
 
dgcnn_pytorch的原作者昨天在代码里加上了可视化的部分，您可以去看看。链接：https://github.com/AnTao97/dgcnn.pytorch
 我也提问过相关可视化的问题在issue里，链接：AnTao97/dgcnn.pytorch#26
